#!/bin/bash
HOME=/home/mayer
mkdir $HOME/opt
mkdir $HOME/share


NCORES=$1

function load {
    export PATH=$HOME/opt/bin:$PATH
    export LD_LIBRARY_PATH=$HOME/opt/lib64:$LD_LIBRARY_PATH
}

function hwloc_install {
    cd $HOME/share    
    wget https://download.open-mpi.org/release/hwloc/v2.2/hwloc-2.2.0.tar.gz
    tar xzf hwloc-2.2.0.tar.gz
    rm hwloc-2.2.0.tar.gz
    cd hwloc-2.2.0
    ./configure --prefix=$HOME/mayer/opt
    make -j $NCORES
    make install       
}

function gmx_install_mpi {

    
    
    cd $HOME/share
    wget http://ftp.gromacs.org/pub/gromacs/gromacs-2020.tar.gz
    tar xzf gromacs-2020.tar.gz
    rm gromacs-2020.tar.gz
    cd gromacs-2020
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX=${HOME}/opt -DREGRESSIONTEST_DOWNLOAD=ON -DGMX_BUILD_OWN_FFTW=ON -DGMX_SIMD=AVX_256 -DGMX_MPI=ON -DGMX_GPU=OFF    
    
    make -j $(NCORES)
    make check -j $(NCORES)    
    make install   
    cd $HOME/share
    rm -r gromacs-2020  
}

function gmx_install_gpu {    
    
    cd $HOME/share
    wget http://ftp.gromacs.org/pub/gromacs/gromacs-2020.tar.gz
    tar xzf gromacs-2020.tar.gz
    rm gromacs-2020.tar.gz
    cd gromacs-2020
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX=${HOME}/opt -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DREGRESSIONTEST_DOWNLOAD=ON -DGMX_GPU=ON -DGMX_BUILD_OWN_FFTW=ON -DGMX_SIMD=AVX_256 -DGMX_MPI=ON -DGMX_DEFAULT_SUFFIX=OFF
        
    make -j $(NCORES)
    make check -j $(NCORES)    
    make install 
    cd $HOME/share
    rm -r gromacs-2020    
}

load
#hwloc_install
#gmx_install_mpi
gmx_install_gpu

