#!/bin/bash
HOME=/home/mayer
mkdir $HOME/opt2
mkdir $HOME/share2

function make_openmpi {

    cd $HOME/share2
    wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.3.tar.gz
    tar xzf openmpi-4.0.3.tar.gz
    cd openmpi-4.0.3
    ./configure --prefix=$HOME/opt2
    make all install
}

function make_boost {

    cd $HOME/share2
    wget https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.gz
    tar xzf boost_1_73_0.tar.gz
    cd boost_1_73_0
    ./bootstrap.sh --prefix=$HOME/opt2
    ./b2 install
}

# base c++ cluster
make_openmpi
make_boost

export PATH=$HOME/opt2/bin:$PATH
export LD_LIBRARY_PATH=$HOME/opt2/lib64:$LD_LIBRARY_PATH


