#!/bin/bash
HOME=/home/mayer
mkdir $HOME/opt
mkdir $HOME/share

cd $HOME/share

wget ftp://ftp.mpi-sb.mpg.de/pub/gnu/mirror/gcc.gnu.org/pub/gcc/releases/gcc-9.3.0/gcc-9.3.0.tar.gz
tar xzf gcc-9.3.0
cd gcc-9.3.0
./contrib/download_prerequisites
cd ..
mkdir objdir
cd objdir
$PWD/../gcc-9.3.0/configure --prefix=$HOME/opt/ --enable-languages=c,c++,fortran --disable-multilib
make -j
make install

export PATH=$HOME/opt/bin:$PATH
export LD_LIBRARY_PATH=$HOME/opt/lib64:$LD_LIBRARY_PATH

cd $HOME/share
wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.3.tar.gz
tar xzf openmpi-4.0.3.tar.gz
cd openmpi-4.0.3
./configure --prefix=$HOME/opt
make all install

cd $HOME/share
wget https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.gz
tar xzf boost_1_73_0.tar.gz
cd boost_1_73_0
./bootstrap.sh --prefix=$HOME/opt
./b2 install


